# Generated by Django 6.0.6 on 2026-07-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
